### ISSUE TITLE
Internal links not parsed?

### ISSUE THREAD

**Issue by RaymiiOrg** [simonfrey/save_to_web.archive.org#1]
<pre>
$ go run main.go https://raymii.org/s/      
2018/06/12 11:27:21 Save URL:  https://raymii.org/s/
2018/06/12 11:27:21 1 : https://raymii.org/s/
http://91.198.137.181:3128
2018/06/12 11:27:24 2 : https://raymii.org/s/feed.xml
2018/06/12 11:27:24 3 : https://raymii.org/s/inc/img/banner_trans.png
2018/06/12 11:27:24 Found 3 subelements on https://raymii.org/s/
2018/06/12 11:27:24 [ 0 ] Try for  https://raymii.org/s/
2018/06/12 11:27:50 Added:  https://raymii.org/s/
2018/06/12 11:27:50 [ 0 ] Try for  https://raymii.org/s/feed.xml
2018/06/12 11:28:04 Added:  https://raymii.org/s/feed.xml
2018/06/12 11:28:04 [ 0 ] Try for  https://raymii.org/s/inc/img/banner_trans.png
2018/06/12 11:28:20 [ 1 ] Try for  https://raymii.org/s/inc/img/banner_trans.png
2018/06/12 11:28:38 Added:  https://raymii.org/s/inc/img/banner_trans.png
2018/06/12 11:28:38 Done
</pre>

But I do have internal links:

<pre>
 a href="blog/That_time_one_of_my_HP-UX_machines_lost_half_its_ram_openssh_7.3_ilo_2.html"
</pre>

**Comment by simonfrey** [comment]
Actually the tool checks if there is a domainname upfront.

I will change it to admire also internal links!

Thanks for your feedback

**Comment by simonfrey** [comment]
You now also can parse internal urls.

For using that feature pass the `-i` flag to the tool. (See README for further documentation)

**Comment by RaymiiOrg** [comment]
Seems to work now, thanks!

`   $ go run main.go -i https://raymii.org/s/
2018/06/19 14:04:01 
 Save URL: https://raymii.org/s/
 Use Proxy: false
 Crawl internal urls: true
2018/06/19 14:04:01 1 : https://raymii.org/s/
2018/06/19 14:04:01 2 : https://raymii.org/s/feed.xml
2018/06/19 14:04:01 3 : https://raymii.org/s/software/ingsoc.html
2018/06/19 14:04:01 4 : https://raymii.org/s/software/Sparkling_Network.html
2018/06/19 14:04:01 5 : https://raymii.org/s/static/About.html
2018/06/19 14:04:01 6 : https://raymii.org/s/inc/img/resistor-50.png
2018/06/19 14:04:01 7 : https://raymii.org/s/inc/img/banner_trans.png
2018/06/19 14:04:01 8 : https://raymii.org/s/index.html
2018/06/19 14:04:01 9 : https://raymii.org/s/tags/all.html
2018/06/19 14:04:01 10 : https://raymii.org/s/tags/articles.html
2018/06/19 14:04:01 11 : https://raymii.org/s/tags/blog.html
2018/06/19 14:04:01 12 : https://raymii.org/s/tags/tutorials.html
2018/06/19 14:04:01 13 : https://raymii.org/s/tags/ansible.html
2018/06/19 14:04:01 14 : https://raymii.org/s/tags/openstack.html
2018/06/19 14:04:01 15 : https://raymii.org/s/tags/openvms.html
2018/06/19 14:04:01 16 : https://raymii.org/s/tags/pdp-8.html
`
