### ISSUE TITLE
Remove Proxy

### ISSUE THREAD

**Issue by SoftCreatR** [simonfrey/save_to_web.archive.org#2]
A version without a proxy would be nice. You can't scrape bigger websites without paying the gimmeproxy API.

**Comment by simonfrey** [comment]
Thanks for that feedback!

I will make a addition version with a proxy flag.

Should be done in the next few days.

**Comment by simonfrey** [comment]
Proxys are now optional. You can use them (if you want so) via the `-p` flag

**Comment by SoftCreatR** [comment]
Thank you, will try that :)

**Comment by SoftCreatR** [comment]
Works well. Thank you again.
