### ISSUE TITLE
Could it be possible to put a delay between the request to Archive.org.

### ISSUE THREAD

**Issue by mikhoul** [simonfrey/save_to_web.archive.org#3]
First Thanks for this useful program. 👍

Even better a random delay between 5-15 seconds option to not being tagged as a bot would help.

![image](https://user-images.githubusercontent.com/5678673/105109359-661b8b80-5a8a-11eb-832d-dbcf2f72a01f.png)

Right now saving some page take 47 retry.... I don't know if it's normal ? 

Regards :octocat:

**Comment by simonfrey** [comment]
Done with https://github.com/simonfrey/save_to_web.archive.org/commit/eb9c2e2d4b64c4d8b9841275144ead4d4c55e8c0

Thanks for that input. You can also use the proxy options to not be marked as bot. 

If you like my work I am very thankfull [for a tip :D](https://simon-frey.com/tip)
